All instructions lifted
Vector35/Z80 pull request #10
Opened 2024-03-02 15:58 UTC by samrussell

2024-03-02 16:02 UTC, plafosse commented
Very cool! Thanks for the PR!

2024-03-04 04:29 UTC, xusheng6 commented
I will be reviewing this

2025-01-09 07:05 UTC, samrussell commented
Hi guys, any chance someone could take a look at this? I can break it into smaller pieces if that makes life easier

2025-01-09 17:05 UTC, galenbwill commented
I will prioritize reviewing it.

2026-07-16 21:55 UTC, psifertex commented
Dang, I'm sorry we let this one lapse. We weren't tracking it on our main tasking board. I'm moving it there so we don't lose it again. My apologies.

2026-07-17 06:21 UTC, samrussell commented
Better late than never :)

2026-07-17 16:35 UTC, xusheng6 requested changes
I found a few issues in the code. Once these are fixed, it should be good to go.

Sorry again for our late resoonse. I will respond promptly once you get these addressed!

2026-07-17 16:35 UTC, xusheng6 commented on Z80IL.py
> +        il.append(il.store(1, il.reg(2, 'HL'), temp0))
This should be il.reg(1, temp0) instead of just temp0. temp0 is the index of the temp register, using it directly does not refer to the register. This also happens on line 757, 773, 792

2026-07-17 16:35 UTC, xusheng6 commented on Z80IL.py
> +        il.append(il.if_expr(il.or_expr(1, il.flag('z'), il.neg_expr(1, il.flag('pv'))), label_done, label_loop))
neg_expr does arithemetic negation, not logical, so I believe the condition is wrong. Same pattern on line 544

2026-07-17 16:35 UTC, xusheng6 commented on Z80IL.py
> +        lower_nybble = il.xor_expr(1, il.const(1, 0x0F), il.reg(1, 'A'))
I think this should be an and instead of xor, in order to extract the bits

Also as a comment, for instructions like DAA, we usually (e.g., for x86) just lift it as an intrinsic rather than spelling out the entire computation. I am not against your doing it like this since z80 is simple enough, so it is practical to do it for all instructions, but I am a bit worried that it hurts readability than helps it. After all this is merely a suggestion, you do not have to change anything

2026-07-17 16:35 UTC, xusheng6 commented on Z80IL.py
> +            il.append(il.set_flag('c', il.test_bit(1, temp0, il.const(1, 1))))
il.test_bit tests the bit at the given index, there is no need to do `1<<7` -- just pass in il.const(1, 7). Same pattern at line 681

2026-07-17 16:35 UTC, xusheng6 commented on Z80IL.py
> +        tmp = il.sub(1, tmp, il.const(1, 1), 'z')
This will incorrectly update the value of the z flag, which DJNZ does not modify. You could try something like this:

```
  result = il.sub(1, il.reg(1, 'B'), il.const(1, 1))
  il.append(il.set_reg(1, 'B', result))

  condition = il.compare_not_equal(
      1,
      il.reg(1, 'B'),
      il.const(1, 0)
  )
  il.append(il.if_expr(condition, label_loop, label_continue))
```

2026-07-17 16:35 UTC, xusheng6 commented on Z80IL.py
> +        il.append(il.set_flag('pv', il.compare_equal(2, il.reg(2, 'BC'), il.const(2, 0))))
I think the condition here is inverted -- it should be il.compare_not_equal

2026-08-19 20:40 UTC, plafosse commented
Unfortunately looks like we're going to have to slip this one to the next release.

2026-08-20 15:34 UTC, merged

2026-08-20 15:48 UTC, xusheng6 commented
Thanks a lot @samrussell!! I made the changes and merged the PR

2026-08-20 16:04 UTC, samrussell commented
Thanks Xusheng, didn't get a chance to implementing myself, glad to get it
all merged

On Thu, Aug 20, 2026, 17:48 xusheng ***@***.***> wrote:

> *xusheng6* left a comment (Vector35/Z80#10)
> <https://github.com/Vector35/Z80/pull/10#issuecomment-5358311318>
>
> Thanks a lot @samrussell <https://github.com/samrussell>!! I made the
> changes and merged the PR
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Vector35/Z80/pull/10?email_source=notifications&email_token=AALJUP7HYVNCFCBYHRYFBMT5K4MWJA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMZVHAZTCMJTGE4KM4TFMFZW63VHNVSW45DJN5XKKZLWMVXHJLDGN5XXIZLSL5RWY2LDNM#issuecomment-5358311318>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALJUP4CDRBAZWDBG362AXD5K4MWJAVCNFSNUABFKJSXA33TNF2G64TZHMZDAMBWG43TSMZYHNEXG43VMU5TEMJWGQ4DMOBSHA2KC5QC>
> .
> Triage notifications, keep track of coding agent tasks and review pull
> requests on the go with GitHub Mobile for iOS
> <https://github.com/notifications/mobile/ios/AALJUP2CLYH3YYNCBYMKQM35K4MWJA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMZVHAZTCMJTGE4KM4TFMFZW63VHNVSW45DJN5XKKZLWMVXHJKTGN5XXIZLSL5UW64Y>
> and Android
> <https://github.com/notifications/mobile/android/AALJUP4JETPJYNC6VLXMLAD5K4MWJA5CNFSNUABFM5UWIORPF5TWS5BNNB2WEL2JONZXKZKDN5WW2ZLOOQXTKMZVHAZTCMJTGE4KM4TFMFZW63VHNVSW45DJN5XKKZLWMVXHJLTGN5XXIZLSL5QW4ZDSN5UWI>.
> Download it today!
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>